select * from customer

--Total revenue generated by male vs female customers
select gender,sum(purchase_amount) as revenue
from customer
group by gender

--which customer use discount but still spent more than avg purchase amount
select customer_id,purchase_amount
from customer
where discount_applied ='Yes' and purchase_amount >= (select Avg(purchase_amount)from customer)

--top 5 product with highest avg review rating
select item_purchased,avg(review_rating)
from customer
group by item_purchased
order by avg (review_rating) desc limit 5

--compare the avg purchase amount between standard and express shipping
select shipping_type,avg(purchase_amount)
from customer
where shipping_type in('Express','Standard')
group by shipping_type

--Compare avg spend and total revenue between subcribers and non-sub
select subscription_status,count(customer_id),
avg(purchase_amount),sum(purchase_amount)
from customer
group by subscription_status

--which 5 product have highest per of purchase with discount applied
select item_purchased,
100 * sum(case when discount_applied ='Yes' then 1 else 0 end)/count(*) as discount_rate
from customer
group by item_purchased
order by discount_rate desc limit 5

--segment customer into new,returning,loyal based on total no. of previous purchased
--and show the count of each segment
with customer_type as (
select customer_id,previous_purchases,
case when previous_purchases=1 then 'New'
	 when previous_purchases between 2 and 10 then 'Returning'
	 else 'Loyal'
	 end as customer_segment
from customer	 
)
select customer_segment,count(*) as "Number of customers"
from customer_type
group by customer_segment

--what are top 3 most purchased product within each category
select * from (
select item_purchased,category,count(customer_id) as total_orders,
Row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category,item_purchased) ranked_items
where item_rank <=3

--are customers who are repeat buyers(more than 5 perchases)also likely to subscribe
select subscription_status,count(customer_id) as repeat_buyers
from customer
where previous_purchases >5
group by subscription_status

--what is revenue contribution of each age group
select age_group,sum(purchase_amount) as total_revenue
from customer
group by age_group